# Jekyll Defaults
title: Pavan Kumar AV
description: A small and simple site I made to test out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://pavankumarav.github.io/"
github: https://github.com/PavankumarAV/PavankumarAV.github.io
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
- text: Contacts
  url: /contacts/
